### ISSUE TITLE
attempt to index local 'info' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [semlar/WorldFlightMap#4]
Running into an issue that I'm not sure is related to WorldFlightMap, but because it is the only addon I recognize in the error I figured I'd post it here to see if anyone knows what may be causing it and possibly get a fix. Lately, whenever I'm in a group and open my map I get the following error. The error does not occur outside of a being in a group, and it also seems to only affect my hunter character, so far my other alts don't seem to receive the error while in a group and opening the map. Thanks.

2x SharedXML\HelpTip.lua:339: attempt to index local 'info' (a nil value)
[string "@SharedXML\HelpTip.lua"]:339: in function <SharedXML\HelpTip.lua:334>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:3461: in function <FrameXML\UIParent.lua:3447>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function <FrameXML\QuestLogOwnerMixin.lua:9>
[string "=[C]"]: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:439>
[string "=[C]"]: in function `ToggleWorldMap'
[string "@WorldFlightMap\WorldFlightMap-9.0.2.2.lua"]:167: in function `OnEvent'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:99: in function `SignalEvent'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:100: in function `OnEvent'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:110: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:109>

Locals:
self = <unnamed> {
 0 = <userdata>
 GetAlignment = <function> defined @SharedXML\HelpTip.lua:436
 BG = TopBg {
 }
 Matches = <function> defined @SharedXML\HelpTip.lua:585
 OnUpdate = <function> defined @SharedXML\HelpTip.lua:361
 ApplyText = <function> defined @SharedXML\HelpTip.lua:515
 OnShow = <function> defined @SharedXML\HelpTip.lua:329
 ShadowTop = TopShadowTop {
 }
 MatchesSystem = <function> defined @SharedXML\HelpTip.lua:593
 ShadowTopLeft = TopShadowTopLeft {
 }
 width = 226
 GlowTopLeft = TopGlowTopLeft {
 }
 closed = false
 AnchorArrow = <function> defined @SharedXML\HelpTip.lua:534
 GlowBottomRight = TopGlowBottomRight {
 }
 GlowBottomLeft = TopGlowBottomLeft {
 }
 GlowBottom = TopGlowBottom {
 }
 acknowledged = false
 Close = <function> defined @SharedXML\HelpTip.lua:356
 Acknowledge = <function> defined @SharedXML\HelpTip.lua:555
 CloseButton = <unnamed> {
 }
 Arrow = <unnamed> {
 }
 OkayButton = <unnamed> {
 }
 Text = <unnamed> {
 }
 ShadowRight = TopShadowRight {
 }
 ShadowLeft = TopShadowLeft {
 }
 ShadowBottom = TopShadowBottom {
 }
 GlowRight = TopGlowRight {
 }
 HandleAcknowledge = <function> defined @SharedXML\HelpTip.lua:560
 ShadowBottomRight = TopShadowBottomRight {
 }
 ShadowBottomLeft = TopShadowBottomLeft {
 }
 ShadowTopRight = TopShadowTopRight {
 }
 OnLoad = <function> defined @SharedXML\HelpTip.lua:322
 OnHide = <function> defined @SharedXML\HelpTip.lua:334
 Layout = <function> defined @SharedXML\HelpTip.lua:483
 AnchorAndRotate = <function> defined @SharedXML\HelpTip.lua:445
 OnEvent = <function> defined @SharedXML\HelpTip.lua:351
 GetTargetPoint = <function> defined @SharedXML\HelpTip.lua:432
 GlowTopRight = TopGlowTopRight {
 }
 GlowLeft = TopGlowLeft {
 }
 GlowTop = TopGlowTop {
 }
 Init = <function> defined @SharedXML\HelpTip.lua:408
 RotateArrow = <function> defined @SharedXML\HelpTip.lua:541
 GetButtonInfo = <function> defined @SharedXML\HelpTip.lua:440
 Reset = <function> defined @SharedXML\HelpTip.lua:571
}
info = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 GetAlignment = <function> defined @SharedXML\HelpTip.lua:436
 BG = TopBg {
 }
 Matches = <function> defined @SharedXML\HelpTip.lua:585
 OnUpdate = <function> defined @SharedXML\HelpTip.lua:361
 ApplyText = <function> defined @SharedXML\HelpTip.lua:515
 OnShow = <function> defined @SharedXML\HelpTip.lua:329
 ShadowTop = TopShadowTop {
 }
 MatchesSystem = <function> defined @SharedXML\HelpTip.lua:593
 ShadowTopLeft = TopShadowTopLeft {
 }
 width = 226
 GlowTopLeft = TopGlowTopLeft {
 }
 closed = false
 AnchorArrow = <function> defined @SharedXML\HelpTip.lua:534
 GlowBottomRight = TopGlowBottomRight {
 }
 GlowBottomLeft = TopGlowBottomLeft {
 }
 GlowBottom = TopGlowBottom {
 }
 acknowledged = false
 Close = <function> defined @SharedXML\HelpTip.lua:356
 Acknowledge = <function> defined @SharedXML\HelpTip.lua:555
 CloseButton = <unnamed> {
 }
 Arrow = <unnamed> {
 }
 OkayButton = <unnamed> {
 }
 Text = <unnamed> {
 }
 ShadowRight = TopShadowRight {
 }
 ShadowLeft = TopShadowLeft {
 }
 ShadowBottom = TopShadowBottom {
 }
 GlowRight = TopGlowRight {
 }
 HandleAcknowledge = <function> defined @SharedXML\HelpTip.lua:560
 ShadowBottomRight = TopShadowBottomRight {
 }
 ShadowBottomLeft = TopShadowBottomLeft {
 }
 ShadowTopRight = TopShadowTopRight {
 }
 OnLoad = <function> defined @SharedXML\HelpTip.lua:322
 OnHide = <function> defined @SharedXML\HelpTip.lua:334
 Layout = <function> defined @SharedXML\HelpTip.lua:483
 AnchorAndRotate = <function> defined @SharedXML\HelpTip.lua:445
 OnEvent = <function> defined @SharedXML\HelpTip.lua:351
 GetTargetPoint = <function> defined @SharedXML\HelpTip.lua:432
 GlowTopRight = TopGlowTopRight {
 }
 GlowLeft = TopGlowLeft {
 }
 GlowTop = TopGl

**Comment by semlar** [comment]
I'm going to close this issue as it has been a year and I have not received any reports from other users experiencing similar errors.

If anyone is able to reproduce this, please let me know!
